i have no idea what i'm doing with my life

diff --git a/boobstrap.in b/boobstrap.in
--- a/boobstrap.in
+++ b/boobstrap.in
@@ -1,47 +1,56 @@
-#!/bin/bash
+#!/bin/sh -
 
 mkbootstrap() {
-	if [ "$1" = "crux_gnulinux" ] || [ "$1" = "gentoo_gnulinux" ] || [ "$1" = "slackware_gnulinux" ]; then
-		shift
-	else
-		echo "Sorry, only CRUX GNU/Linux supported at this time."
-		exit 0
-	fi
-	
-	local DIRECTORY
-	local PORTS_TREE
-	local PORTS_LIST
-	local PORTS
+	case "$1" in
+		"crux_gnulinux")
+			shift
+			;;
+		"archlinux_gnulinux"|"arch_gnulinux")
+			shift
+			pacstrap "$@"
+			exit 0
+			;;
+		"debian_gnulinux")
+			shift
+			debootstrap "$@"
+			exit 0
+			;;
+		*)
+			cat <<"EOF"
+crux_gnulinux
+archlinux_gnulinux (pacstrap)
+debian_gnulinux (debootstrap)
+EOF
+			exit 0
+			;;
+	esac
 
-	while [ "$1" ]; do
+	while test "$1"; do
 		case "$1" in
 			"--ports-dir")
-				PORTS_TREE=(${PORTS_TREE[@]} $2)
+				PORTS_TREE="$PORTS_TREE $2"
 				shift
 				;;
 			*)
 				if [ -z "$DIRECTORY" ]; then
 					DIRECTORY="$1"
 				else
-					PORTS_LIST=(${PORTS_LIST[@]} $1)
+					PORTS_LIST="$PORTS_LIST $1"
 				fi
 				;;
 		esac
 		shift
 	done
 
-	local dir
-	local prt
-	local chk
-	for dir in ${PORTS_TREE[@]}; do
+	for dir in $PORTS_TREE; do
 		for prt in $dir/*; do
-			if [ "${#PORTS_LIST[@]}" = "0" ]; then
-				PORTS=(${PORTS[@]} $prt)
+			if [ "$PORTS_LIST" = "" ]; then
+				PORTS="$PORTS $prt"
 			else
-				for chk in ${PORTS_LIST[@]}; do
+				for chk in $PORTS_LIST; do
 					case $prt in
-						*"/$chk") PORTS=(${PORTS[@]} $prt) ;;
-						*"/$chk#"*) PORTS=(${PORTS[@]} $prt) ;;
+						*"/$chk") PORTS="$PORTS $prt" ;;
+						*"/$chk#"*) PORTS="$PORTS $prt" ;;
 					esac
 				done
 			fi
@@ -51,7 +60,7 @@ mkbootstrap() {
 	mkdir $DIRECTORY/var/lib/pkg -p
 	touch $DIRECTORY/var/lib/pkg/db
 
-	for prt in ${PORTS[@]}; do
+	for prt in $PORTS; do
 		echo -n "Install: $prt"
 		pkgadd --root $DIRECTORY $prt
 		if [ "$?" = "0" ]; then
@@ -62,24 +71,57 @@ mkbootstrap() {
 	done
 }
 
-mkinitramfs() {
-	local DIRECTORY
-	local STANDALONE_MODE
-	local OVERLAY_MODE
-	local OVERLAYS
-	local COMMAND
-	local NUM
-	local OUTPUT
+pkgadd() {
+	CHROOT="/"
 
-	while [ "$1" ]; do
+	# NOTABUG
+	# behavior like original pkgadd
+	while test "$2"; do
+		case "$1" in
+			"--root"|"-r")
+				CHROOT="$2"
+				shift
+				;;
+			*)
+				echo "invalid option $1"
+				exit 1
+				;;
+		esac
+		shift
+	done
+
+	name="${1}"
+	name="${name##*/}"
+	name="${name%%.pkg*}"
+	name="${name%%\#*}"
+
+	version="${1}"
+	version="${version##*/}"
+	version="${version%%.pkg*}"
+	version="${version##*\#}"
+
+	echo "$name" >> $CHROOT/var/lib/pkg/db
+	echo "$version" >> $CHROOT/var/lib/pkg/db
+	tar xpvf $1 --xattrs-include='*.*' --numeric-owner -C $CHROOT >> $CHROOT/var/lib/pkg/db
+	echo "" >> $CHROOT/var/lib/pkg/db
+}
+
+mkinitramfs() {
+	DIRECTORY=""
+	STANDALONE_MODE=""
+	OVERLAY_MODE=""
+	OVERLAYS=""
+	COMMAND=""
+	OUTPUT=""
+
+	while test "$1"; do
 		case "$1" in
 			"--standalone")
 				STANDALONE_MODE="+"
-				shift
 				;;
 			"--overlay")
 				OVERLAY_MODE="+"
-				OVERLAYS=(${OVERLAYS[@]} $2)
+				OVERLAYS="$OVERLAYS $2"
 				shift
 				;;
 			"--command")
@@ -91,7 +133,7 @@ mkinitramfs() {
 				shift
 				;;
 			*)
-				if [ -z "$DIRECTORY" ]; then
+				if test "$DIRECTORY" = ""; then
 					DIRECTORY="$1"
 				fi
 				;;
@@ -110,49 +152,43 @@ mkinitramfs() {
 	if [ "$OVERLAY_MODE" ]; then
 
 		case $COMMAND in
-			"") COMMAND="cp -a {source} {destination}" ;;
-			"{template:squashfs:xz}") COMMAND="mksquashfs {source} {destination} -b 1048576 -comp xz -Xdict-size 100% -noappend" ;;
+			"") COMMAND="cp -a \${SOURCE} \${DESTINATION}" ;;
+			"\${SQUASHFS_XZ}") COMMAND="mksquashfs \${SOURCE} \${DESTINATION} -b 1048576 -comp xz -Xdict-size 100%" ;;
 		esac
 
 		mkinitramfs_copy_env $DIRECTORY
 
 		NUM=0
 
-		for overlay in ${OVERLAYS[@]}; do
+		for overlay in $OVERLAYS; do
 
-			NUM=$(($NUM + 10))
+			NUM="$(($NUM + 10))"
+			SOURCE="$overlay"
+			DESTINATION="$DIRECTORY/overlays/$NUM-overlay"
 
-			COMMAND=${COMMAND//"{source}"/$overlay}
-			COMMAND=${COMMAND//"{destination}"/$DIRECTORY/overlays/$NUM-overlay}
-
-			sh -c "$COMMAND"
+			eval "$COMMAND"
 
 		done
 
 	fi
 
-	pushd $DIRECTORY
+	cd $DIRECTORY
 	case $OUTPUT in
-		""|"-") mkinitramfs_cpio ;;
-		*) mkinitramfs_cpio > $OUTPUT ;;
+		""|"-") find . -print0 | cpio --null --create --format=newc --verbose ;;
+		*) find . -print0 | cpio --null --create --format=newc --verbose > $OUTPUT ;;
 	esac
-	popd
-}
-
-mkinitramfs_cpio() {
-	find . -print0 | cpio --null --create --format=newc --verbose
 }
 
 mkinitramfs_copy_bin() {
-	local src="$1"
-	local dst="$2"
-	local dep=""
+	src="$1"
+	dst="$2"
+	dep=""
 
 	if [ "$dst" = "" ]; then
 		dst="$src"
 	fi
 
-	if [ -a "$DIRECTORY$dst" ]; then
+	if [ -e "$DIRECTORY$dst" ]; then
 		return
 	fi
 
@@ -164,9 +200,9 @@ mkinitramfs_copy_bin() {
 }
 
 mkinitramfs_copy_env() {
-	local DIRECTORY="$1"
+	DIRECTORY="$1"
 
-	for dir in proc sys dev run mnt overlay{,s}; do
+	for dir in proc sys dev run mnt overlay overlays; do
 		install -d -m 0755 $DIRECTORY/$dir
 	done
 
@@ -184,7 +220,7 @@ mkinitramfs_copy_env() {
 }
 
 mkbootisofs() {
-	local DIRECTORY="$1"
+	DIRECTORY="$1"
 
 	mkdir -p $DIRECTORY/boot
 	mkdir -p $DIRECTORY/boot/grub
@@ -213,7 +249,7 @@ mkbootisofs() {
 		--themes="starfield" \
 		"/boot/grub/grub.cfg=$DIRECTORY/boot/grub/grub.cfg"
 
-	local temporarely_mountpoint=$(mktemp -d)
+	temporarely_mountpoint=$(mktemp -d)
 	dd if=/dev/zero of=$DIRECTORY/boot/grub/uefi.img status=none count=8 bs=1M
 	mkdosfs $DIRECTORY/boot/grub/uefi.img
 	mount $DIRECTORY/boot/grub/uefi.img $temporarely_mountpoint
@@ -221,6 +257,7 @@ mkbootisofs() {
 	mkdir $temporarely_mountpoint/EFI/BOOT
 	cp $DIRECTORY/boot/grub/grub.efi $temporarely_mountpoint/EFI/BOOT/BOOTX64.EFI
 	umount $temporarely_mountpoint
+	rmdir $temporarely_mountpoint
 
 	xorriso -as mkisofs \
 		-iso-level 3 \
@@ -242,22 +279,85 @@ mkbootisofs() {
 		"$DIRECTORY" 2>/dev/null
 }
 
-main() {
-	local COMMAND
+mktest() {
+	BOOTIMG="$1"
+	WORKDIR="$2"
 
-	COMMAND="${0##*/}"
-	
-	if [ "$COMMAND" = "boobstrap" ]; then
-		COMMAND="$1"
-		shift
+	mkdir -p "$WORKDIR/cruxmedia"
+
+	mount "$BOOTIMG" "$WORKDIR/cruxmedia"
+
+	mkdir -p "$WORKDIR/bootstrap"
+
+	mkbootstrap crux_gnulinux "$WORKDIR/bootstrap" --ports-dir "$WORKDIR/cruxmedia/crux/core"
+
+	mkdir -p "$WORKDIR/initramfs"
+
+	mkinitramfs "$WORKDIR/initramfs" \
+		--overlay "$WORKDIR/bootstrap" \
+		--output "$WORKDIR/initramfs.img" \
+		--command "mksquashfs \${SOURCE} \${DESTINATION} -b 1048576 -comp xz -Xdict-size 100%"
+
+	mkdir -p "$WORKDIR/bootimage"
+	mkdir -p "$WORKDIR/bootimage/boot"
+
+	for f in "/boot/vmlinuz-"* "/lib/modules/"*"/vmlinuz"; do
+		if test -f "$f"; then
+			cp "$f" "$WORKDIR/bootimage/boot/vmlinuz"
+		fi
+	done
+
+	mv "$WORKDIR/initramfs.img" "$WORKDIR/bootimage/boot/initrd"
+
+	mkdir -p "$WORKDIR/bootimage/crux"
+	mkdir -p "$WORKDIR/bootimage/crux/core"
+
+	cp -a "$WORKDIR/cruxmedia/crux/core" "$WORKDIR/bootimage/crux"
+
+	mkbootisofs "$WORKDIR/bootimage" > "$WORKDIR/bootimage.iso"
+
+	umount "$WORKDIR/cruxmedia"
+}
+
+main()
+{
+	PROGNAME="${0##*/}"
+
+	if test "$PROGNAME" = "boobstrap"; then
+
+		PROGNAME="$1"
+
+		if test "$2"; then
+			shift
+		fi
 	fi
 
-	case $COMMAND in
-		"mkbootstrap") mkbootstrap "$@" ;;
-		"mkinitramfs") mkinitramfs "$@" ;;
-		"mkbootisofs") mkbootisofs "$@" ;;
-		*) echo WUT? ;;
+	case "$PROGNAME" in
+		"mkbootstrap")
+			mkbootstrap "$@"
+			;;
+		"mkinitramfs")
+			mkinitramfs "$@"
+			;;
+		"mkbootisofs")
+			mkbootisofs "$@"
+			;;
+		"mktest")
+			mktest "$@"
+			;;
+		*)
+			rtfm
+			;;
 	esac
+}
+
+rtfm()
+{
+	cat <<"EOF"
+WUT?
+EOF
+
+	exit 0
 }
 
 get_config_init() {
@@ -286,13 +386,13 @@ mkdir -p $workdir
 
 for overlay in /overlays/*; do
 
-	overlay_mount="${overlay##*/}"
+	overlay_mount="/overlay/${overlay##*/}"
 
-	lowerdir="overlay/$overlay_mount:$lowerdir"
+	lowerdir="$overlay_mount:$lowerdir"
 
-	mkdir -p overlay/$overlay_mount
+	mkdir -p $overlay_mount
 
-	mount -t squashfs -o ro $overlay overlay/$overlay_mount
+	mount -t squashfs -o ro $overlay $overlay_mount
 
 done
 
