added nice colours

diff --git a/boobstrap.in b/boobstrap.in
--- a/boobstrap.in
+++ b/boobstrap.in
@@ -1,5 +1,9 @@
 #! /bin/sh -
 
+#
+# RUNTIME LIBRARY
+#
+
 lddtree() {
 	if test "$1" = ""; then
 		return 0
@@ -72,15 +76,20 @@ importroot() {
 		hi
 		cd "$DIR"
 		cpio --extract --make-directories --format "newc" --quiet >/dev/null 2>&1
-		case "$?" in
-			"0") echo "Import success." | msg -2 ;;
-			*) echo "Import failed." | msg -2 ;;
+		CODE="$?"
+		case "$CODE" in
+			"0")
+				echo "Import success" | msg -2 --foreground "Light Green"
+				;;
+			*)
+				echo "Import failed [$CODE]" | msg -2 --foreground "Brown"
+				;;
 		esac
 		cd "$OLDPWD"
 		lo
 		echo "Done [$DIR]" | msg -2
 	else
-		echo "No such directory [$DIR]" | msg -2
+		echo "No such directory [$DIR] for import" | msg -2 --foreground "Brown"
 	fi
 }
 
@@ -101,15 +110,20 @@ exportroot() {
 		hi
 		cd "$DIR"
 		find . -print0 | cpio --create --format "newc" --null --quiet 2>/dev/null
-		case "$?" in
-			"0") echo "Export success." | msg -2 ;;
-			*) echo "Export failed." | msg -2 ;;
+		CODE="$?"
+		case "$CODE" in
+			"0")
+				echo "Export success" | msg -2 --foreground "Light Green"
+				;;
+			*)
+				echo "Export failed" | msg -2 msg -2 --foreground "Brown"
+				;;
 		esac
 		cd "$OLDPWD"
 		lo
 		echo "Done [$DIR]" | msg -2
 	else
-		echo "No such directory [$DIR]" | msg -2
+		echo "No such directory [$DIR] for export" | msg -2 --foreground "Brown"
 	fi
 }
 
@@ -168,28 +182,29 @@ cruxstrap() {
 		echo "Packages ignored because none found." | msg -2
 		hi
 		for prt in $IGNORED; do
-			echo "Ignored: $prt" | msg -2
+			echo "$prt" | msg -2 --foreground "Light Red" --highlight
 		done
 		lo
 	fi
 
 	if test "$INSTALL"; then
 		echo "Packages to install: $(echo $INSTALL | wc -w)" | msg -1
-		hi
-
 		mkdir -p "$CHROOT/var/lib/pkg" 2>/dev/null
 		touch "$CHROOT/var/lib/pkg/db" 2>/dev/null
-
+		hi
 		for prt in $INSTALL; do
 			name="$(basename $prt)"
 			name="${name%%#*}"
 			pkgadd --root "$CHROOT" "$prt"
 			case "$?" in
-				"0") echo "Install: $name" | msg -1 ;;
-				*) echo "Error: $name" | msg -1 ;;
+				"0")
+					echo "$name" | msg -1 --foreground "Light Green"
+					;;
+				*)
+					echo "$name" | msg -1 --foreground "Light Red" --highlight
+					;;
 			esac
 		done
-
 		lo
 		echo "Done [$CHROOT]" | msg -1
 	else
@@ -240,39 +255,59 @@ mkinitramfs() {
 		echo "Creating system directories" | msg -2
 		hi
 		for dir in "proc" "sys" "dev" "run" "merged" "overlay" "overlays"; do
-			echo "[/$dir]" | msg -2
-			hi
 			mkdir -p $CHROOT/$dir 2>/dev/null
-			case "$?" in
-				"0") ;;
-				*) echo "Failure [$?]" | msg -2 ;;
+			CODE="$?"
+			case "$CODE" in
+				"0")
+					echo "/$dir" | msg -2 --foreground "Light Blue"
+					;;
+				*)
+					echo "/$dir" | msg -2 --foreground "Light Red" --highlight
+					hi
+					echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+					lo
+					;;
 			esac
-			lo
 		done
 		lo
 
 		echo "Copying devices" | msg -2
 		hi
 		for dev in "console" "tty" "tty1" "null"; do
-			echo "[/dev/$dev]" | msg -2
-			hi
 			cp -a "/dev/$dev" "$CHROOT/dev/$dev" 2>/dev/null
-			case "$?" in
-				"0") ;;
-				*) echo "Failure [$?]" | msg -2 ;;
+			CODE="$?"
+			case "$CODE" in
+				"0")
+					echo "/dev/$dev" | msg -2 --foreground "Light Blue"
+					;;
+				*)
+					echo "/dev/$dev" | msg -2 --foreground "Light Red" --highlight
+					hi
+					echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+					lo
+					;;
 			esac
-			lo
 		done
 		lo
 
 		echo "Copying system files" | msg -2
 		hi
 		for bin in "sh" "switch_root" "mount" "umount" "mkdir" "rmdir" "mv"; do
-
-			echo "[$bin]" | msg -2
-
+			which $bin 1>/dev/null 2>/dev/null
+			CODE="$?"
+			case "$CODE" in
+				"0")
+					echo "$bin" | msg -2 --foreground "Light Blue"
+					;;
+				*)
+					CODE=""
+					echo "$bin" | msg -2 --foreground "Light Red" --highlight
+					hi
+					echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+					lo
+					;;
+			esac
 			deps=""
-			code=""
 			for dep in $(lddtree $(which $bin)); do
 				deps="$deps $dep"
 
@@ -281,31 +316,41 @@ mkinitramfs() {
 				fi
 
 				install -D "$dep" "$CHROOT$dep" 2>/dev/null
-				code="$?"
+				CODE="$?"
 			done
-
-			deps=$(echo $deps | tr ' ' '\n' | sort | uniq | tr '\n' ' ')
 			hi
-			for dep in $deps; do
-				echo "$dep" | msg -2
-				hi
-				case "$code" in
-					"0") ;;
-					*) echo "Failure [$code]" | msg -2 ;;
+			for dep in $(echo $deps | tr ' ' '\n' | sort | uniq | tr '\n' ' '); do
+				case "$CODE" in
+					"0")
+						echo "$dep" | msg -2 --foreground "Purple"
+						;;
+					*)
+						CODE=""
+						echo "$dep" | msg -2 --foreground "Light Red" --highlight
+						hi
+						echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+						lo
+						;;
 				esac
-				lo
 			done
 			lo
 		done
 		lo
 
-		echo "Creating init [/init]" | msg -2
+		echo "Creating init" | msg -2
 		hi
+		echo "/init" | msg -2 --foreground "Light Blue"
 		get_config_init > "$CHROOT/init" 2>/dev/null
-		case "$?" in
-			"0") chmod +x "$CHROOT/init" 2>/dev/null ;;
-			*) echo "Failure [$?]" | msg -2 ;;
+		chmod +x "$CHROOT/init" 2>/dev/null
+		CODE="$?"
+		hi
+		case "$CODE" in
+			"0") ;;
+			*)
+				echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+				;;
 		esac
+		lo
 		lo
 
 		if test "$COMMAND" = ""; then
@@ -320,12 +365,20 @@ mkinitramfs() {
 			NUM="$(($NUM + 10))"
 			SOURCE="$overlay"
 			DESTINATION="$CHROOT/overlays/$NUM-$(basename $overlay)"
-			echo "Do: $COMMAND" | msg -2
-			hi
+			echo "$COMMAND" | msg -2 --foreground "Light Blue"
 			eval "$COMMAND" 1>&2
-			case "$?" in
-				"0") echo "OK" | msg -2 ;;
-				*) echo "Failure [$?]" | msg -2 ;;
+			CODE="$?"
+			hi
+			case "$CODE" in
+				"0")
+					echo "Success" | msg -2 --foreground "Light Green"
+					;;
+				*)
+					echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+					hi
+					echo "$COMMAND" | msg -2 --foreground "Light Red" --highlight
+					lo
+					;;
 			esac
 			lo
 		done
@@ -337,14 +390,18 @@ mkinitramfs() {
 	echo "Creating initramfs [$IMAGE]" | msg -2
 
 	cd "$CHROOT" 2>/dev/null
-	hi
 	case "$IMAGE" in
 		""|"-") find . -print0 | cpio --create --format "newc" --null --quiet 2>/dev/null ; STATUS="$?" ;;
 		*) find . -print0 | cpio --create --format "newc" --null --quiet > "$IMAGE" 2>/dev/null ; STATUS="$?" ;;
 	esac
+	hi
 	case "$STATUS" in
-		"0") ;;
-		*) echo "Failure [$STATUS]" | msg -2 ;;
+		"0")
+			echo "Success" | msg -2 --foreground "Light Green"
+			;;
+		*)
+			echo "Error while generating initramfs" | msg -2 --foreground "Brown" --highlight
+			;;
 	esac
 	lo
 	cd "$OLDPWD" 2>/dev/null
@@ -379,7 +436,7 @@ mkbootisofs() {
 	hi
 
 	if test -d "$DIR/boot"; then
-		echo "Writing grub configuration" | msg -2
+		echo "Writing grub configuration" | msg -2 --foreground "Purple"
 		hi
 
 		mkdir "$DIR/boot/grub" 2>/dev/null
@@ -388,12 +445,12 @@ mkbootisofs() {
 
 		case "$?" in
 			"0") ;;
-			*) echo "Failure [$?]" | msg -2 ;;
+			*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 		esac
 		lo
 	fi
 
-	echo "Generate BIOS bootloader" | msg -2
+	echo "Generate BIOS bootloader" | msg -2 --foreground "Purple"
 	hi
 
 	grub-mkstandalone \
@@ -409,22 +466,22 @@ mkbootisofs() {
 
 	case "$?" in
 		"0") ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 	lo
 
-	echo "Copying BIOS bootloader" | msg -2
+	echo "Copying BIOS bootloader" | msg -2 --foreground "Purple"
 	hi
 
 	cat "$GRUB_i386_CDBOOT" "$DIR/boot/grub/grub.raw" > "$DIR/boot/grub/bios.img" 2>/dev/null
 
 	case "$?" in
 		"0") ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 	lo
 
-	echo "Generate UEFI bootloader" | msg -2
+	echo "Generate UEFI bootloader" | msg -2 --foreground "Purple"
 	hi
 
 	grub-mkstandalone \
@@ -440,59 +497,59 @@ mkbootisofs() {
 
 	case "$?" in
 		"0") ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 
-	echo "Creating UEFI (FAT32) partition" | msg -2
+	echo "Creating UEFI (FAT32) partition" | msg -2 --foreground "Purple"
 	hi
 
-	echo "Writing empty partition" | msg -2
+	echo "Writing empty partition" | msg -2 --foreground "Purple"
 	hi
 	truncate -s "10MB" "$DIR/boot/grub/uefi.img" 2>/dev/null
 	case "$?" in
 		"0") ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 	lo
 
-	echo "Formatting empty partition to FAT32" | msg -2
+	echo "Formatting empty partition to FAT32" | msg -2 --foreground "Purple"
 	hi
 	mkdosfs "$DIR/boot/grub/uefi.img" 2>/dev/null
 	case "$?" in
 		"0") ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 	lo
 
-	echo "Mounting UEFI (FAT32) partition" | msg -2
+	echo "Mounting UEFI (FAT32) partition" | msg -2 --foreground "Purple"
 	hi
 	mkdir "$DIR/uefi" 2>/dev/null
 	mount "$DIR/boot/grub/uefi.img" "$DIR/uefi" 2>/dev/null
 	case "$?" in
 		"0") ;;
-		"32") echo "root priveleges required for mount" | msg -2 ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		"32") echo "root priveleges required for mount" | msg -2 --foreground "Light Red" --highlight ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 	lo
 
-	echo "Copying UEFI bootloader to UEFI (FAT32) partition" | msg -2
+	echo "Copying UEFI bootloader to UEFI (FAT32) partition" | msg -2 --foreground "Purple"
 	hi
 	mkdir "$DIR/uefi/EFI" 2>/dev/null
 	mkdir "$DIR/uefi/EFI/BOOT" 2>/dev/null
 	cp "$DIR/boot/grub/grub.efi" "$DIR/uefi/EFI/BOOT/BOOTX64.EFI" 2>/dev/null
 	case "$?" in
 		"0") ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 	lo
 
-	echo "Unmounting UEFI (FAT32) partition" | msg -2
+	echo "Unmounting UEFI (FAT32) partition" | msg -2 --foreground "Purple"
 	hi
 	umount "$DIR/uefi" 2>/dev/null
 	case "$?" in
 		"0") ;;
-		"32") echo "root priveleges required for umount" | msg -2 ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		"32") echo "root priveleges required for umount" | msg -2 --foreground "Light Red" --highlight ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 	lo
 
@@ -501,7 +558,7 @@ mkbootisofs() {
 	lo
 	lo
 
-	echo "Writing BIOS/UEFI bootable ISO image [$IMAGE]" | msg -2
+	echo "Writing BIOS/UEFI bootable ISO image [$IMAGE]" | msg -2 --foreground "Purple"
 	hi
 
 	xorriso -as "mkisofs" \
@@ -525,7 +582,7 @@ mkbootisofs() {
 
 	case "$?" in
 		"0") ;;
-		*) echo "Failure [$?]" | msg -2 ;;
+		*) echo "Failure [$?]" | msg -2 --foreground "Brown" ;;
 	esac
 	lo
 
@@ -546,7 +603,7 @@ boobstrap_build() {
 	done
 
 	if test "$DIR" = ""; then
-		DIR="$(mktemp -d -p $PWD)"
+		DIR="$(mktemp -d -p $PWD 2>/dev/null)"
 	fi
 
 	if test -f "/usr/share/boobstrap/bootstrap-templates/$TEMPLATE"; then
@@ -560,20 +617,25 @@ boobstrap_build() {
 	fi
 
 	if test -f "$TEMPLATE"; then
+		echo "Building configuration [$TEMPLATE]" | msg -2
 		hi
-		echo "Building configuration [${TEMPLATE##*/}]" | msg -2
 		eval $TEMPLATE $DIR
-		case "$?" in
-			"0") echo "Done [${TEMPLATE##*/}]" | msg -2 ;;
-			*) echo "Failed [${TEMPLATE##*/}]" | msg -2 ;;
-		esac
+		STATUS="$?"
 		lo
+		case "$STATUS" in
+			"0") echo "Done [$TEMPLATE]" | msg -2 ;;
+			*) echo "Failed [$TEMPLATE]" | msg -2 ;;
+		esac
 	fi
 }
 
 boobstrap_run() {
 	boobstrap_build "$@"
 }
+
+#
+# CORE
+#
 
 main() {
 	PROGNAME="$(basename $0)"
@@ -615,32 +677,64 @@ lo() {
 msg() {
 	STDOUT=""
 	STDERR=""
+	fore=""
+	back=""
+	ctrl=""
+	sgr0=""
 
 	while test "$1"; do
 		case "$1" in
 			"-1") STDOUT="yes" ;;
 			"-2") STDERR="yes" ;;
+			"--foreground") fore="$2" ; shift ; ;;
+			"--background") back="$2" ; shift ; ;;
+			"--highlight") ctrl="$ctrl$(tput blink)" ; ;;
+			"--bold") ctrl="$ctrl$(tput bold)" ; ;;
 		esac
 		shift
 	done
 
+	case "$fore" in
+		"03"|"3"|"Green") fore="$(tput setaf 2)" ;;
+		"09"|"9"|"Light Green") fore="$(tput setaf 2)$(tput bold)" ;;
+		"04"|"4"|"Light Red") fore="$(tput setaf 1)$(tput bold)" ;;
+		"05"|"5"|"Brown") fore="$(tput setaf 1)" ;;
+		"06"|"6"|"Purple") fore="$(tput setaf 5)" ;;
+		"12"|"Light Blue") fore="$(tput setaf 4)$(tput bold)" ;;
+		"13"|"Pink") fore="$(tput setaf 5)$(tput bold)" ;;
+		*) fore="$(tput setaf 2)" ;;
+	esac
+
+	if test "$ctrl$fore$back"; then
+		sgr0="$(tput sgr0)"
+	fi
+
+	if test "$COLOURS" = "none"; then
+		fore=""
+		back=""
+		ctrl=""
+		sgr0=""
+	fi
+
 	if test "$STDOUT" = "yes"; then
 		while read input; do
-			echo "$ECHO_INDENT$input" >&1
+			echo "$ECHO_INDENT$ctrl$fore$back$input$sgr0" >&1
 		done
 	fi
 
 	if test "$STDERR" = "yes"; then
 		while read input; do
-			echo "$ECHO_INDENT$input" >&2
+			echo "$ECHO_INDENT$ctrl$fore$back$input$sgr0" >&2
 		done
 	fi
 }
 
 rtfm() {
-	cat <<"EOF"
-WUT?
-EOF
+	while read input; do
+		case "$input" in
+			"# "*) echo "${input%%# *}" ;;
+		esac
+	done < "$0"
 }
 
 get_config_init() {
@@ -716,7 +810,7 @@ EOF
 
 preflight_checks() {
 	for dep in "grub-mkstandalone" "mkdosfs" "xorriso"; do
-		which "$dep" 1>"/dev/null" 2>"/dev/null"
+		which "$dep" 1>/dev/null 2>/dev/null
 		case "$?" in
 			"0") ;;
 			*) TEST="x" ;;
@@ -764,6 +858,20 @@ preflight_checks() {
 		echo "continue to running without any font." | msg -2
 	else
 		GRUB_FONT="/boot/grub/font.pf2=$GRUB_FONT"
+	fi
+
+	if test "$COLOURS" = ""; then
+		if which tput 1>/dev/null 2>/dev/null; then
+			COLOURS="auto"
+		else
+			COLOURS="none"
+		fi
+	fi
+
+	if test -f "$HOME/.boobstrap.conf"; then
+		. "$HOME/.boobstrap.conf" 2>/dev/null || echo "$HOME/.boobstrap.conf contain errors!" | msg -2
+	elif test -f "/etc/boobstrap.conf"; then
+		. "/etc/boobstrap.conf" 2>/dev/null || echo "/etc/boobstrap.conf contain errors!" | msg -2
 	fi
 }
 
