added color configuration

diff --git a/boobstrap.in b/boobstrap.in
--- a/boobstrap.in
+++ b/boobstrap.in
@@ -1,53 +1,8 @@
 #! /bin/sh -
 
 #
-# RUNTIME LIBRARY
+# CORE
 #
-
-lddtree() {
-	if test "$1" = ""; then
-		return 0
-	fi
-
-	echo "$1"
-
-	for dep in $(ldd "$1" | grep -o '/.* '); do
-		lddtree "$dep"
-	done
-}
-
-pkgadd() {
-	CHROOT="/"
-
-	# NOTABUG
-	# behavior like original pkgadd
-	while test "$2"; do
-		case "$1" in
-			"--root"|"-r") CHROOT="$2" ; shift ;;
-			*) echo "invalid option $1" 1>&2 ; return 1 ;;
-		esac
-		shift
-	done
-
-	name="${1}"
-	name="${name##*/}"
-	name="${name%%.pkg*}"
-	name="${name%%\#*}"
-
-	version="${1}"
-	version="${version##*/}"
-	version="${version%%.pkg*}"
-	version="${version##*\#}"
-
-	echo "$name" >> "$CHROOT/var/lib/pkg/db" 2>/dev/null		|| return 1
-	echo "$version" >> "$CHROOT/var/lib/pkg/db" 2>/dev/null		|| return 1
-	tar -xpvf "$1" \
-		--xattrs-include="*.*" \
-		--numeric-owner \
-		--directory "$CHROOT" >> "$CHROOT/var/lib/pkg/db" \
-		2>/dev/null						|| return 1
-	echo "" >> "$CHROOT/var/lib/pkg/db" 2>/dev/null			|| return 1
-}
 
 mkbootstrap() {
 	case "$1" in
@@ -57,162 +12,6 @@ mkbootstrap() {
 		"archlinux_gnulinux"|"arch_gnulinux") shift ; pacstrap "$@" ;;
 		"debian_gnulinux") shift ; debootstrap "$@" ;;
 	esac
-}
-
-importroot() {
-	DIR=""
-	while test "$1"; do
-		case "$1" in
-			*)
-				if test "$DIR" = ""; then
-					DIR="$1"
-				fi
-				;;
-		esac
-		shift
-	done
-	if test -d "$DIR"; then
-		echo "Import chroot [$DIR]" | msg -2
-		hi
-		cd "$DIR"
-		cpio --extract --make-directories --format "newc" --quiet >/dev/null 2>&1
-		CODE="$?"
-		case "$CODE" in
-			"0")
-				echo "Import success" | msg -2 --foreground "Light Green"
-				;;
-			*)
-				echo "Import failed [$CODE]" | msg -2 --foreground "Brown"
-				;;
-		esac
-		cd "$OLDPWD"
-		lo
-		echo "Done [$DIR]" | msg -2
-	else
-		echo "No such directory [$DIR] for import" | msg -2 --foreground "Brown"
-	fi
-}
-
-exportroot() {
-	DIR=""
-	while test "$1"; do
-		case "$1" in
-			*)
-				if test "$DIR" = ""; then
-					DIR="$1"
-				fi
-				;;
-		esac
-		shift
-	done
-	if test -d "$DIR"; then
-		echo "Export chroot [$DIR]" | msg -2
-		hi
-		cd "$DIR"
-		find . -print0 | cpio --create --format "newc" --null --quiet 2>/dev/null
-		CODE="$?"
-		case "$CODE" in
-			"0")
-				echo "Export success" | msg -2 --foreground "Light Green"
-				;;
-			*)
-				echo "Export failed" | msg -2 msg -2 --foreground "Brown"
-				;;
-		esac
-		cd "$OLDPWD"
-		lo
-		echo "Done [$DIR]" | msg -2
-	else
-		echo "No such directory [$DIR] for export" | msg -2 --foreground "Brown"
-	fi
-}
-
-cruxstrap() {
-	CHROOT=""
-	PORTS=""
-	PACKAGES=""
-	INSTALL=""
-	IGNORED=""
-
-	while test "$1"; do
-		case "$1" in
-			"--ports-dir") PORTS="$PORTS $2" ; shift ;;
-			*)
-				if test "$CHROOT" = ""; then
-					CHROOT="$1"
-				else
-					PACKAGES="$PACKAGES $1"
-				fi
-				;;
-		esac
-		shift
-	done
-
-	echo "Bootstrapping [$CHROOT]" | msg -1
-	hi
-
-	if test "$PACKAGES" = ""; then
-		for dir in $PORTS; do
-			for prt in "$dir/"*; do
-				INSTALL="$INSTALL $(realpath $prt)"
-			done
-		done
-	else
-		for pkg in $PACKAGES; do
-			if test -f "$pkg"; then
-				INSTALL="$INSTALL $(realpath $pkg)"
-			else
-				FAILURE="y"
-				for dir in $PORTS; do
-					for prt in "$dir/"*; do
-						case "$prt" in
-							*"/$pkg") INSTALL="$INSTALL $(realpath $prt)" ; FAILURE="" ;;
-							*"/$pkg#"*) INSTALL="$INSTALL $(realpath $prt)" ; FAILURE="" ;;
-						esac
-					done
-				done
-			fi
-			if test "$FAILURE" = "y"; then
-				IGNORED="$IGNORED $pkg"
-			fi
-		done
-	fi
-
-	if test "$IGNORED"; then
-		echo "Packages ignored because none found." | msg -2
-		hi
-		for prt in $IGNORED; do
-			echo "$prt" | msg -2 --foreground "Light Red" --highlight
-		done
-		lo
-	fi
-
-	if test "$INSTALL"; then
-		echo "Packages to install: $(echo $INSTALL | wc -w)" | msg -1
-		mkdir -p "$CHROOT/var/lib/pkg" 2>/dev/null
-		touch "$CHROOT/var/lib/pkg/db" 2>/dev/null
-		hi
-		for prt in $INSTALL; do
-			name="$(basename $prt)"
-			name="${name%%#*}"
-			pkgadd --root "$CHROOT" "$prt"
-			case "$?" in
-				"0")
-					echo "$name" | msg -1 --foreground "Light Green"
-					;;
-				*)
-					echo "$name" | msg -1 --foreground "Light Red" --highlight
-					;;
-			esac
-		done
-		lo
-		echo "Done [$CHROOT]" | msg -1
-	else
-		echo "No packages selected. Nothing to do." | msg -1
-	fi
-
-	lo
-	echo "Done [$CHROOT]" | msg -1
 }
 
 mkinitramfs() {
@@ -253,113 +52,13 @@ mkinitramfs() {
 
 	if test "$IS_OVERLAY" = "yes"; then
 
-		echo "Creating system directories" | msg -2
-		hi
-		for dir in "proc" "sys" "dev" "run" "merged" "overlay" "overlays"; do
-			mkdir -p $CHROOT/$dir 2>/dev/null
-			CODE="$?"
-			case "$CODE" in
-				"0")
-					echo "/$dir" | msg -2 --foreground "Light Blue"
-					;;
-				*)
-					echo "/$dir" | msg -2 --foreground "Light Red" --highlight
-					hi
-					echo "Failure [$CODE]" | msg -2 --foreground "Brown"
-					lo
-					;;
-			esac
-		done
-		lo
+		rd_make_dir "$CHROOT"
 
-		echo "Copying devices" | msg -2
-		hi
-		for dev in "console" "tty" "tty1" "null"; do
-			cp -a "/dev/$dev" "$CHROOT/dev/$dev" 2>/dev/null
-			CODE="$?"
-			case "$CODE" in
-				"0")
-					echo "/dev/$dev" | msg -2 --foreground "Light Blue"
-					;;
-				*)
-					echo "/dev/$dev" | msg -2 --foreground "Light Red" --highlight
-					hi
-					echo "Failure [$CODE]" | msg -2 --foreground "Brown"
-					lo
-					;;
-			esac
-		done
-		lo
+		rd_copy_dev "$CHROOT"
 
-		echo "Copying system files" | msg -2
+		rd_copy_bin "$CHROOT"
 
-		SYSTEMWIDE_BINARIES="$(initramfs_systemwide_bin 2>/dev/null)"
-
-		if test "$SYSTEMWIDE_BINARIES" = ""; then
-			SYSTEMWIDE_BINARIES="sh switch_root mount umount mkdir rmdir mv"
-		fi
-
-		hi
-		for bin in $SYSTEMWIDE_BINARIES; do
-			which $bin 1>/dev/null 2>/dev/null
-			CODE="$?"
-			case "$CODE" in
-				"0")
-					echo "$bin" | msg -2 --foreground "Light Blue"
-					;;
-				*)
-					CODE=""
-					echo "$bin" | msg -2 --foreground "Light Red" --highlight
-					hi
-					echo "Failure [$CODE]" | msg -2 --foreground "Brown"
-					lo
-					;;
-			esac
-			deps=""
-			for dep in $(lddtree $(which $bin)); do
-				deps="$deps $dep"
-
-				if test -f "$CHROOT$dep"; then
-					continue
-				fi
-
-				install -D "$dep" "$CHROOT$dep" 2>/dev/null
-				CODE="$?"
-			done
-			hi
-			for dep in $(echo $deps | tr ' ' '\n' | sort | uniq | tr '\n' ' '); do
-				case "$CODE" in
-					"0")
-						echo "$dep" | msg -2 --foreground "Purple"
-						;;
-					*)
-						CODE=""
-						echo "$dep" | msg -2 --foreground "Light Red" --highlight
-						hi
-						echo "Failure [$CODE]" | msg -2 --foreground "Brown"
-						lo
-						;;
-				esac
-			done
-			lo
-		done
-		lo
-
-		echo "Creating init" | msg -2
-		hi
-		echo "/init" | msg -2 --foreground "Light Blue"
-		initramfs_init > "$CHROOT/init" 2>/dev/null
-		chmod +x "$CHROOT/init" 2>/dev/null
-		CODE="$?"
-		hi
-		case "$CODE" in
-			"0") ;;
-			*)
-				echo "Failure [$CODE]" | msg -2 --foreground "Brown"
-				;;
-		esac
-		lo
-		lo
+		rd_gen_init "$CHROOT"
 
 		if test "$COMMAND" = ""; then
 			COMMAND="cp -a \${SOURCE} \${DESTINATION} 2>/dev/null"
@@ -391,7 +90,6 @@ mkinitramfs() {
 			lo
 		done
 		lo
-
 		echo "Overlays done" | msg -2
 	fi
 
@@ -598,6 +296,253 @@ mkbootisofs() {
 	echo "Done [$DIR]" | msg -2
 }
 
+#
+# RUNTIME LIBRARY
+#
+
+lddtree() {
+	if test "$1" = ""; then
+		return 0
+	fi
+
+	echo "$1"
+
+	for dep in $(ldd "$1" | grep -o '/.* '); do
+		lddtree "$dep"
+	done
+}
+
+pkgadd() {
+	CHROOT="/"
+
+	# NOTABUG
+	# behavior like original pkgadd
+	while test "$2"; do
+		case "$1" in
+			"--root"|"-r") CHROOT="$2" ; shift ;;
+			*) echo "invalid option $1" 1>&2 ; return 1 ;;
+		esac
+		shift
+	done
+
+	name="${1}"
+	name="${name##*/}"
+	name="${name%%.pkg*}"
+	name="${name%%\#*}"
+
+	version="${1}"
+	version="${version##*/}"
+	version="${version%%.pkg*}"
+	version="${version##*\#}"
+
+	echo "$name" >> "$CHROOT/var/lib/pkg/db" 2>/dev/null		|| return 1
+	echo "$version" >> "$CHROOT/var/lib/pkg/db" 2>/dev/null		|| return 1
+	tar -xpvf "$1" \
+		--xattrs-include="*.*" \
+		--numeric-owner \
+		--directory "$CHROOT" >> "$CHROOT/var/lib/pkg/db" \
+		2>/dev/null						|| return 1
+	echo "" >> "$CHROOT/var/lib/pkg/db" 2>/dev/null			|| return 1
+}
+
+hi() {
+	export ECHO_INDENT="$ECHO_INDENT  "
+}
+
+lo() {
+	export ECHO_INDENT="${ECHO_INDENT%??}"
+}
+
+msg() {
+	STDOUT=""
+	STDERR=""
+	fore=""
+	back=""
+	ctrl=""
+	sgr0=""
+	while test "$1"; do
+		case "$1" in
+			"-1")		STDOUT="yes" ;;
+			"-2")		STDERR="yes" ;;
+			"--foreground")	fore="$2" ; shift ; ;;
+			"--background")	back="$2" ; shift ; ;;
+			"--highlight")	ctrl="$ctrl$SWITCH_HIGHLIGHT" ; ;;
+			"--bold")	ctrl="$ctrl$SWITCH_BOLD" ; ;;
+		esac
+		shift
+	done
+	case "$fore" in
+		"00"|"0"|"White")	fore="$FOREGROUND_00" ;;
+		"01"|"1"|"Black")	fore="$FOREGROUND_01" ;;
+		"02"|"2"|"Blue")	fore="$FOREGROUND_02" ;;
+		"03"|"3"|"Green")	fore="$FOREGROUND_03" ;;
+		"04"|"4"|"Light Red")	fore="$FOREGROUND_04" ;;
+		"05"|"5"|"Brown")	fore="$FOREGROUND_05" ;;
+		"06"|"6"|"Purple")	fore="$FOREGROUND_06" ;;
+		"07"|"7"|"Orange")	fore="$FOREGROUND_07" ;;
+		"08"|"8"|"Yellow")	fore="$FOREGROUND_08" ;;
+		"09"|"9"|"Light Green")	fore="$FOREGROUND_09" ;;
+		"10"|"Cyan")		fore="$FOREGROUND_10" ;;
+		"11"|"Light Cyan")	fore="$FOREGROUND_11" ;;
+		"12"|"Light Blue")	fore="$FOREGROUND_12" ;;
+		"13"|"Pink")		fore="$FOREGROUND_13" ;;
+		"14"|"Grey")		fore="$FOREGROUND_14" ;;
+		"15"|"Light Grey")	fore="$FOREGROUND_15" ;;
+		*)			fore="$FOREGROUND_DEFAULT" ;;
+	esac
+	case "$back" in
+		"00"|"0"|"White")	back="$BACKGROUND_00" ;;
+		"01"|"1"|"Black")	back="$BACKGROUND_01" ;;
+		"02"|"2"|"Blue")	back="$BACKGROUND_02" ;;
+		"03"|"3"|"Green")	back="$BACKGROUND_03" ;;
+		"04"|"4"|"Light Red")	back="$BACKGROUND_04" ;;
+		"05"|"5"|"Brown")	back="$BACKGROUND_05" ;;
+		"06"|"6"|"Purple")	back="$BACKGROUND_06" ;;
+		"07"|"7"|"Orange")	back="$BACKGROUND_07" ;;
+		"08"|"8"|"Yellow")	back="$BACKGROUND_08" ;;
+		"09"|"9"|"Light Green")	back="$BACKGROUND_09" ;;
+		"10"|"Cyan")		back="$BACKGROUND_10" ;;
+		"11"|"Light Cyan")	back="$BACKGROUND_11" ;;
+		"12"|"Light Blue")	back="$BACKGROUND_12" ;;
+		"13"|"Pink")		back="$BACKGROUND_13" ;;
+		"14"|"Grey")		back="$BACKGROUND_14" ;;
+		"15"|"Light Grey")	back="$BACKGROUND_15" ;;
+		*)			back="$BACKGROUND_DEFAULT" ;;
+	esac
+	if test "$fore$back$ctrl"; then
+		sgr0="$(tput sgr0)"
+	fi
+	if test "$COLOURS" = "none"; then
+		fore=""
+		back=""
+		ctrl=""
+		sgr0=""
+	fi
+	if test "$STDOUT" = "yes"; then
+		while read input; do
+			echo "$ECHO_INDENT$fore$back$ctrl$input$sgr0" >&1
+		done
+	fi
+	if test "$STDERR" = "yes"; then
+		while read input; do
+			echo "$ECHO_INDENT$fore$back$ctrl$input$sgr0" >&2
+		done
+	fi
+}
+
+rd_copy_dev() {
+	echo "Copying devices" | msg -2
+	hi
+	for dev in "console" "tty" "tty1" "null"; do
+		cp -a "/dev/$dev" "$1/dev/$dev" 2>/dev/null
+		CODE="$?"
+		case "$CODE" in
+			"0")
+				echo "/dev/$dev" | msg -2 --foreground "Light Blue"
+				;;
+			*)
+				echo "/dev/$dev" | msg -2 --foreground "Light Red" --highlight
+				hi
+				echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+				lo
+				;;
+		esac
+	done
+	lo
+}
+
+rd_copy_bin() {
+	echo "Copying system files" | msg -2
+	hi
+	SYSTEMWIDE_BINARIES="$(initramfs_systemwide_bin 2>/dev/null)"
+	if test "$SYSTEMWIDE_BINARIES" = ""; then
+		SYSTEMWIDE_BINARIES="sh switch_root mount umount mkdir rmdir mv"
+	fi
+	for bin in $SYSTEMWIDE_BINARIES; do
+		which $bin 1>/dev/null 2>/dev/null
+		CODE="$?"
+		case "$CODE" in
+			"0")
+				echo "$bin" | msg -2 --foreground "Light Blue"
+				;;
+			*)
+				CODE=""
+				echo "$bin" | msg -2 --foreground "Light Red" --highlight
+				hi
+				echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+				lo
+				;;
+		esac
+		deps=""
+		for dep in $(lddtree $(which $bin)); do
+			deps="$deps $dep"
+
+			if test -f "$1$dep"; then
+				continue
+			fi
+
+			install -D "$dep" "$1$dep" 2>/dev/null
+			CODE="$?"
+		done
+		hi
+		for dep in $(echo $deps | tr ' ' '\n' | sort | uniq | tr '\n' ' '); do
+			case "$CODE" in
+				"0")
+					echo "$dep" | msg -2 --foreground "Purple"
+					;;
+				*)
+					CODE=""
+					echo "$dep" | msg -2 --foreground "Light Red" --highlight
+					hi
+					echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+					lo
+					;;
+			esac
+		done
+		lo
+	done
+	lo
+}
+
+rd_gen_init() {
+	echo "Creating init" | msg -2
+	hi
+	echo "/init" | msg -2 --foreground "Light Blue"
+	initramfs_init > "$1/init" 2>/dev/null
+	chmod +x "$1/init" 2>/dev/null
+	CODE="$?"
+	case "$CODE" in
+		"0") ;;
+		*)
+			hi
+			echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+			lo
+			;;
+	esac
+	lo
+}
+
+rd_make_dir() {
+	echo "Creating system directories" | msg -2
+	hi
+	for dir in "proc" "sys" "dev" "run" "merged" "overlay" "overlays"; do
+		mkdir -p $1/$dir 2>/dev/null
+		CODE="$?"
+		case "$CODE" in
+			"0")
+				echo "/$dir" | msg -2 --foreground "Light Blue"
+				;;
+			*)
+				echo "/$dir" | msg -2 --foreground "Light Red" --highlight
+				hi
+				echo "Failure [$CODE]" | msg -2 --foreground "Brown"
+				lo
+				;;
+		esac
+	done
+	lo
+}
+
 boobstrap_build() {
 	DIR=""
 	TEMPLATE=""
@@ -641,9 +586,161 @@ boobstrap_run() {
 	boobstrap_build "$@"
 }
 
-#
-# CORE
-#
+importroot() {
+	DIR=""
+	while test "$1"; do
+		case "$1" in
+			*)
+				if test "$DIR" = ""; then
+					DIR="$1"
+				fi
+				;;
+		esac
+		shift
+	done
+	if test -d "$DIR"; then
+		echo "Import chroot [$DIR]" | msg -2
+		hi
+		cd "$DIR"
+		cpio --extract --make-directories --format "newc" --quiet >/dev/null 2>&1
+		CODE="$?"
+		case "$CODE" in
+			"0")
+				echo "Import success" | msg -2 --foreground "Light Green"
+				;;
+			*)
+				echo "Import failed [$CODE]" | msg -2 --foreground "Brown"
+				;;
+		esac
+		cd "$OLDPWD"
+		lo
+		echo "Done [$DIR]" | msg -2
+	else
+		echo "No such directory [$DIR] for import" | msg -2 --foreground "Brown"
+	fi
+}
+
+exportroot() {
+	DIR=""
+	while test "$1"; do
+		case "$1" in
+			*)
+				if test "$DIR" = ""; then
+					DIR="$1"
+				fi
+				;;
+		esac
+		shift
+	done
+	if test -d "$DIR"; then
+		echo "Export chroot [$DIR]" | msg -2
+		hi
+		cd "$DIR"
+		find . -print0 | cpio --create --format "newc" --null --quiet 2>/dev/null
+		CODE="$?"
+		case "$CODE" in
+			"0")
+				echo "Export success" | msg -2 --foreground "Light Green"
+				;;
+			*)
+				echo "Export failed" | msg -2 msg -2 --foreground "Brown"
+				;;
+		esac
+		cd "$OLDPWD"
+		lo
+		echo "Done [$DIR]" | msg -2
+	else
+		echo "No such directory [$DIR] for export" | msg -2 --foreground "Brown"
+	fi
+}
+
+cruxstrap() {
+	CHROOT=""
+	PORTS=""
+	PACKAGES=""
+	INSTALL=""
+	IGNORED=""
+
+	while test "$1"; do
+		case "$1" in
+			"--ports-dir") PORTS="$PORTS $2" ; shift ;;
+			*)
+				if test "$CHROOT" = ""; then
+					CHROOT="$1"
+				else
+					PACKAGES="$PACKAGES $1"
+				fi
+				;;
+		esac
+		shift
+	done
+
+	echo "Bootstrapping [$CHROOT]" | msg -1
+	hi
+
+	if test "$PACKAGES" = ""; then
+		for dir in $PORTS; do
+			for prt in "$dir/"*; do
+				INSTALL="$INSTALL $(realpath $prt)"
+			done
+		done
+	else
+		for pkg in $PACKAGES; do
+			if test -f "$pkg"; then
+				INSTALL="$INSTALL $(realpath $pkg)"
+			else
+				FAILURE="y"
+				for dir in $PORTS; do
+					for prt in "$dir/"*; do
+						case "$prt" in
+							*"/$pkg") INSTALL="$INSTALL $(realpath $prt)" ; FAILURE="" ;;
+							*"/$pkg#"*) INSTALL="$INSTALL $(realpath $prt)" ; FAILURE="" ;;
+						esac
+					done
+				done
+			fi
+			if test "$FAILURE" = "y"; then
+				IGNORED="$IGNORED $pkg"
+			fi
+		done
+	fi
+
+	if test "$IGNORED"; then
+		echo "Packages ignored because none found." | msg -2
+		hi
+		for prt in $IGNORED; do
+			echo "$prt" | msg -2 --foreground "Light Red" --highlight
+		done
+		lo
+	fi
+
+	if test "$INSTALL"; then
+		echo "Packages to install: $(echo $INSTALL | wc -w)" | msg -1
+		mkdir -p "$CHROOT/var/lib/pkg" 2>/dev/null
+		touch "$CHROOT/var/lib/pkg/db" 2>/dev/null
+		hi
+		for prt in $INSTALL; do
+			name="$(basename $prt)"
+			name="${name%%#*}"
+			pkgadd --root "$CHROOT" "$prt"
+			case "$?" in
+				"0")
+					echo "$name" | msg -1 --foreground "Light Green"
+					;;
+				*)
+					echo "$name" | msg -1 --foreground "Light Red" --highlight
+					;;
+			esac
+		done
+		lo
+		echo "Done [$CHROOT]" | msg -1
+	else
+		echo "No packages selected. Nothing to do." | msg -1
+	fi
+
+	lo
+	echo "Done [$CHROOT]" | msg -1
+}
 
 main() {
 	PROGNAME="$(basename $0)"
@@ -672,69 +769,6 @@ main() {
 		"mkinitramfs") mkinitramfs "$@" ;;
 		"mkbootisofs") mkbootisofs "$@" ;;
 	esac
-}
-
-hi() {
-	export ECHO_INDENT="$ECHO_INDENT  "
-}
-
-lo() {
-	export ECHO_INDENT="${ECHO_INDENT%??}"
-}
-
-msg() {
-	STDOUT=""
-	STDERR=""
-	fore=""
-	back=""
-	ctrl=""
-	sgr0=""
-
-	while test "$1"; do
-		case "$1" in
-			"-1") STDOUT="yes" ;;
-			"-2") STDERR="yes" ;;
-			"--foreground") fore="$2" ; shift ; ;;
-			"--background") back="$2" ; shift ; ;;
-			"--highlight") ctrl="$ctrl$(tput blink)" ; ;;
-			"--bold") ctrl="$ctrl$(tput bold)" ; ;;
-		esac
-		shift
-	done
-
-	case "$fore" in
-		"03"|"3"|"Green") fore="$(tput setaf 2)" ;;
-		"09"|"9"|"Light Green") fore="$(tput setaf 2)$(tput bold)" ;;
-		"04"|"4"|"Light Red") fore="$(tput setaf 1)$(tput bold)" ;;
-		"05"|"5"|"Brown") fore="$(tput setaf 1)" ;;
-		"06"|"6"|"Purple") fore="$(tput setaf 5)" ;;
-		"12"|"Light Blue") fore="$(tput setaf 4)$(tput bold)" ;;
-		"13"|"Pink") fore="$(tput setaf 5)$(tput bold)" ;;
-		*) fore="$(tput setaf 2)" ;;
-	esac
-
-	if test "$ctrl$fore$back"; then
-		sgr0="$(tput sgr0)"
-	fi
-
-	if test "$COLOURS" = "none"; then
-		fore=""
-		back=""
-		ctrl=""
-		sgr0=""
-	fi
-
-	if test "$STDOUT" = "yes"; then
-		while read input; do
-			echo "$ECHO_INDENT$ctrl$fore$back$input$sgr0" >&1
-		done
-	fi
-
-	if test "$STDERR" = "yes"; then
-		while read input; do
-			echo "$ECHO_INDENT$ctrl$fore$back$input$sgr0" >&2
-		done
-	fi
 }
 
 rtfm() {
@@ -832,6 +866,10 @@ preflight_checks() {
 		else
 			COLOURS="none"
 		fi
+	fi
+
+	if test "$COLOURS" = "auto"; then
+		set_color_theme 2>/dev/null
 	fi
 }
 
