BUMP 1.1

diff --git a/init.in b/init.in
--- a/init.in
+++ b/init.in
@@ -17,7 +17,11 @@ search_media() {
 		mount -r "/dev/$dev" "/media" 2>/dev/null
 		if test "$?" = "0"; then
 			if test -d "$@"; then
-				echo "Yes"
+				echo "Searching media done"
+				return 0
+			fi
+			if test -f "$@"; then
+				echo "Searching media done"
 				return 0
 			fi
 			umount "/media"
@@ -28,69 +32,96 @@ search_media() {
 	return 1
 }
 
-catch_all_overlays() {
-	echo "Run overlays"
-	lowerdir=""
-	upperdir="/mnt/overlays/rootfs-changes"
-	workdir="/mnt/overlays/tmp"
-	mkdir -p "/mnt"
-	mkdir -p "/mnt/merged"
-	mkdir -p "/mnt/overlays"
-	mount -t tmpfs tmpfs "/mnt/overlays"
-	mkdir -p "$upperdir"
-	mkdir -p "$workdir"
-	for overlay in "$@/overlays/"*; do
-		echo "Overlay $overlay"
-		source="$overlay"
-		target="/mnt/overlays/${overlay##*/}"
-		case "$overlay" in
-			*".cpio")
-				use_driver_cpio "$source" "$target"
-				CODE="$?"
-				;;
-			*".squashfs")
-				use_driver_squashfs "$source" "$target"
-				CODE="$?"
-				;;
-			*".raw.ext")
-				use_driver_ext "$source" "$target"
-				CODE="$?"
-				;;
-			*)
-				use_driver_directory "$source" "$target"
-				CODE="$?"
-				;;
-		esac
-		if test "$CODE" = "0"; then
-			lowerdir="$target:$lowerdir"
-		else
-			echo "$overlay ERROR"
-		fi
-	done
-	if test "$lowerdir" = ""; then
-		echo "No working overlays found"
-		return 1
+filesystem() {
+	if test "$USE_FILESYSTEM" = "SHMFS"; then
+		FILESYSTEM_MOUNT="/mnt/shm"
 	fi
-	if test "$USE_DRIVER" = "OVERLAY_FS"; then
-		if mount -t overlay -o lowerdir="${lowerdir%?}",upperdir="$upperdir",workdir="$workdir" Overlay_FS "/mnt/merged"; then
-			mkdir -p "/mnt/merged/mnt/overlays"
-			mount -o bind,ro "/mnt/overlays" "/mnt/merged/mnt/overlays"
-			echo "Install merged tmpfs as rootfs"
-			return 0
-		else
-			echo "Check for CONFIG_OVERLAY_FS"
+	if test "$USE_FILESYSTEM" = "OVERLAY_FS"; then
+		FILESYSTEM_MOUNT="/mnt/overlay"
+		mkdir -p "$FILESYSTEM_MOUNT"
+		mount -t tmpfs tmpfs "$FILESYSTEM_MOUNT"
+
+		OVERLAY_LOWERDIR=""
+
+		OVERLAY_UPPERDIR="$FILESYSTEM_MOUNT/rootfs-changes"
+		mkdir -p "$OVERLAY_UPPERDIR"
+		
+		OVERLAY_WORK_DIR="$FILESYSTEM_MOUNT/tmp"
+		mkdir -p "$OVERLAY_WORK_DIR"
+
+		echo "Searching filesystem"
+		for fs in $@; do
+			if test -f "$fs"; then
+				if try_filesystem "$fs" on "$FILESYSTEM_MOUNT"; then
+					OVERLAY_LOWERDIR="$(catch_filesystem $fs in $FILESYSTEM_MOUNT):$OVERLAY_LOWERDIR"
+				fi
+			fi
+			if test -d "$fs"; then
+				for f in "$fs/"*; do
+					if try_filesystem "$f" on "$FILESYSTEM_MOUNT"; then
+						OVERLAY_LOWERDIR="$(catch_filesystem $f in $FILESYSTEM_MOUNT):$OVERLAY_LOWERDIR"
+					fi
+				done
+			fi
+		done
+		echo "Searching filesystem done"
+
+		if test "$OVERLAY_LOWERDIR" = ""; then
+			echo "No working filesystem found"
 			return 1
 		fi
+
+		L="${OVERLAY_LOWERDIR%?}"
+		U="$OVERLAY_UPPERDIR"
+		W="$OVERLAY_WORK_DIR"
+
+		if mount -t overlay -o lowerdir="$L",upperdir="$U",workdir="$W" rootfs "$SWITCH_ROOTFS"; then
+			mkdir -p "$SWITCH_ROOTFS$FILESYSTEM_MOUNT"
+			mount -o bind,ro "$FILESYSTEM_MOUNT" "$SWITCH_ROOTFS$FILESYSTEM_MOUNT"
+			echo "Install merged tmpfs as rootfs"
+			return 0
+		fi
+
+		echo "Check /proc/config* for CONFIG_OVERLAY_FS"
+		return 1
+	fi
+}
+
+try_filesystem() {
+	echo "Filesystem $1"
+	case "$1" in
+		*".cpio")
+			use_driver_cpio "$1" "$3/${1##*'/'}"
+			CODE="$?"
+			;;
+		*".sqfs")
+			use_driver_mount "$1" "$3/${1##*'/'}"
+			CODE="$?"
+			;;
+		*)
+			use_driver_copy "$1" "$3/${1##*'/'}"
+			CODE="$?"
+			;;
+	esac
+	if test "$CODE" = "0"; then
+		echo "Filesystem is now on $3/${1##*'/'}"
+	else
+		echo "Filesystem mount failed"
+	fi
+}
+
+catch_filesystem() {
+	if test -d "$3/${1##*'/'}"; then
+		echo "$3/${1##*'/'}"
+		return 0
 	fi
 	return 1
 }
 
-use_driver_directory() {
-	source="$1"
-	target="$2"
-	mkdir -p "$target"
-	if test -d "$source"; then
-		if cp -a "$source/"* "$target" 2>/dev/null; then
+use_driver_copy() {
+	mkdir -p "$2"
+	if test -d "$1"; then
+		if cp -a "$1/"* "$2" 2>/dev/null; then
 			return 0
 		fi
 	fi
@@ -98,43 +129,30 @@ use_driver_directory() {
 }
 
 use_driver_cpio() {
-	source="$1"
-	target="$2"
-	mkdir -p "$target"
-	cd "$target"
-	if cpio -i -d -H "newc" < "$source" 1>/dev/null 2>/dev/null; then
+	mkdir -p "$2"
+	cd "$2"
+	if cpio -i -d -H "newc" < "$1" 1>/dev/null 2>/dev/null; then
 		return 0
 	fi
 	cd "$OLDPWD"
 	return 1
 }
 
-use_driver_squashfs() {
-	source="$1"
-	target="$2"
-	mkdir -p "$target"
-	if mount "$source" "$target"; then
-		return 0
-	fi
-	return 1
-}
-
-use_driver_ext() {
-	source="$1"
-	target="$2"
-	mkdir -p "$target"
-	if mount -o ro "$source" "$target"; then
+use_driver_mount() {
+	mkdir -p "$2"
+	if mount "$1" "$2"; then
 		return 0
 	fi
 	return 1
 }
 
 cheat_sheet() {
-	while "$1"; do
+	while test "$1"; do
 		case "$1" in
-			"boobs.boot-from-ram") BOOT_FROM_RAM="yes" ;;
-			"boobs.use-overlayfs") USE_DRIVER="OVERLAY_FS" ;;
-			"boobs.use-shmfs") USE_DRIVER="SHMFS" ;;
+			"boobs.search-rootfs="*) SEARCH_ROOTFS="${1##*=}" ;;
+			"boobs.copy-to-ram") COPY_TO_RAM="yes" ;;
+			"boobs.use-overlayfs") USE_FILESYSTEM="OVERLAY_FS" ;;
+			"boobs.use-shmfs") USE_FILESYSTEM="SHMFS" ;;
 		esac
 		shift
 	done
@@ -143,9 +161,11 @@ cheat_sheet() {
 main() {
 	echo "Install /proc /sys /dev /run"
 
-	if test -x "/usr/bin/busybox"; then
-		/usr/bin/busybox --install "/usr/bin"
-	fi
+	for dir in "/sbin" "/usr/sbin" "/opt/sbin" "/bin" "/usr/bin" "/opt/bin"; do
+		if test -x "$dir/busybox"; then
+			$dir/busybox --install
+		fi
+	done
 
 	mount -t proc none /proc
 	echo "0" >/proc/sys/kernel/printk
@@ -153,43 +173,55 @@ main() {
 	mount -t devtmpfs none /dev
 	mount -t tmpfs none /run
 
-	while read -r input; do
-		cheat_sheet "$input"
+	while read input; do
+		cheat_sheet $input
 	done < /proc/cmdline
 
 	if test "$SEARCH_ROOTFS" = ""; then
-		SEARCH_ROOTFS="/media/system"
+		SEARCH_ROOTFS="/system/overlays"
 	fi
+
+	SEARCH_ROOTFS="/media$SEARCH_ROOTFS"
 
 	if test "$SWITCH_ROOTFS" = ""; then
 		SWITCH_ROOTFS="/mnt/merged"
+		mkdir -p "$SWITCH_ROOTFS"
+		mount -t tmpfs tmpfs "$SWITCH_ROOTFS"
 	fi
 
-	if test "$BOOT_FROM_RAM" = ""; then
-		BOOT_FROM_RAM="no"
+	if test "$COPY_TO_RAM" = ""; then
+		COPY_TO_RAM="no"
 	fi
 
-	if test "$USE_DRIVER" = ""; then
-		USE_DRIVER="OVERLAY_FS"
+	if test "$USE_FILESYSTEM" = ""; then
+		USE_FILESYSTEM="OVERLAY_FS"
 	fi
 
-	if test -x "/usr/bin/mdev"; then
+	if test -x "$(which mdev)"; then
 		mdev -s
 
 		if search_media "$SEARCH_ROOTFS"; then
-			if test "$BOOT_FROM_RAM" = "yes"; then
-				SEARCH_ROOTFS="/mnt/toram/system"
+			if test "$COPY_TO_RAM" = "yes"; then
+				SWITCH_NEXTFS="/mnt/toram"
 				echo "Start copying system to the RAM drive"
-				mkdir -p "/mnt/toram"
-				mount -t tmpfs -o "size=100%" toram "/mnt/toram"
-				cp -r -v "/media/system" "/mnt/toram"
+				mkdir -p "$SWITCH_NEXTFS"
+				mount -t tmpfs -o "size=100%" toram "$SWITCH_NEXTFS"
+				if test -d "$SEARCH_ROOTFS"; then
+					cp -r -v "$SEARCH_ROOTFS/"* "$SWITCH_NEXTFS"
+				fi
+				if test -f "$SEARCH_ROOTFS"; then
+					SWITCH_NEXTFS="$SWITCH_NEXTFS/${SEARCH_ROOTFS%%*/}"
+					cp -r -v "$SEARCH_ROOTFS" "$SWITCH_NEXTFS"
+				fi
+				SEARCH_ROOTFS="$SWITCH_NEXTFS"
 				echo "Device can be successfully unplugged now"
+				unset SWITCH_NEXTFS
 			fi
 		fi
 	fi
 
-	if catch_all_overlays "$SEARCH_ROOTFS"; then
-		echo "Overlays OK"
+	if filesystem "$SEARCH_ROOTFS"; then
+		echo "Filesystem OK"
 	fi
 
 	echo "Uninstall /proc /sys /dev /run"
